import { TODOS_URL } from "../../api";
import { Todo } from "../../types";
import Head from "next/head";
import { useEffect, useState } from "react";

async function fetchTodos() {
  const response = await fetch(TODOS_URL);
  const json = await response.json();
  return json as Array<Todo>;
}

async function fetchHello() {
  const response = await fetch("/api/hello");
  const json = await response.json();
  return json as { name: string };
}

export default function Home() {
  const [todos, setTodos] = useState<Array<Todo>>([]);
  const [name, setName] = useState("");

  useEffect(() => {
    fetchTodos().then((todos) => setTodos(todos));
    fetchHello().then((hello) => setName(hello.name));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello Planning {name}!</h1>

        <ul>
          {todos?.map((todo) => {
            return <li key={todo.id}>{todo.title}</li>;
          })}
        </ul>
      </main>
    </>
  );
}
